version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: sizing-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/frontend:/usr/share/nginx/html/frontend
      - ./frontend/dashboard:/usr/share/nginx/html/dashboard
    restart: always
