spring:
  application:
    name: sizing
  datasource:
    url: jdbc:mysql://localhost:3306/demo?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: cungvay10
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    stream-read-constraints:
      max-string-length: 104857600  # 100MB
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    clean-disabled: true

server:
  address: 0.0.0.0
  port: 8085
  tomcat:
    max-http-form-post-size: -1
    connection-timeout: 120000ms
    max-swallow-size: -1

logging:
  level:
    root: INFO
    com.example.sizing: DEBUG
    com.example.sizing.controller: INFO
    com.example.sizing.service: DEBUG
    com.example.sizing.security: INFO
    com.example.sizing.exception: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

###